Wire the filibuster with the redis interceptor
filibuster-testing/filibuster-java-instrumentation pull request #125
Opened 2023-05-09 02:46 UTC by MichaelA-ops

2023-05-09 10:00 UTC, cmeiklejohn requested changes

2023-05-09 10:00 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/RedisSingleFaultCommandTimeoutExceptionAnalysisConfigurationFile.java
> +        filibusterAnalysisConfigurationBuilderRedisExceptions.exception("io.lettuce.core.RedisCommandTimeoutException", createErrorMap("Command timed out after 100 millisecond(s)"));
Doesn't match the exception thrown above.  On purpose?

2023-05-09 10:16 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisClientInterceptor.java
> +        FilibusterClientInstrumentor filibusterClientInstrumentor = new FilibusterClientInstrumentor(redisConnectionString, shouldCommunicateWithServer(), contextStorage, callsite);
It's in line 159

2023-05-09 10:17 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisClientInterceptor.java
> +        if (result != null) {
Result can be null if, for example, I query a key that is not in Redis. I will add a test for this.

2023-05-09 10:22 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisClientInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationComplete(Object.class.getName(), returnValueProperties);
Yes, this case is triggered if the result is null (see example above). I will add a test.

2023-05-09 10:23 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisClientInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Should I move it to RedisClientInterceptor instead?

2023-05-09 10:38 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/RedisSingleFaultCommandTimeoutExceptionAnalysisConfigurationFile.java
> +        filibusterAnalysisConfigurationBuilderRedisExceptions.exception("io.lettuce.core.RedisCommandTimeoutException", createErrorMap("Command timed out after 100 millisecond(s)"));
Yes, I wanted first to throw RedisConnectionException, but proceeded for now with RedisCommandTimeoutException since my unit tests handle call get and set. These calls are more likely to cause RedisCommandTimeoutException.

2023-05-09 10:39 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/RedisSingleFaultCommandTimeoutExceptionAnalysisConfigurationFile.java
> +        filibusterAnalysisConfigurationBuilderRedisExceptions.exception("io.lettuce.core.RedisCommandTimeoutException", createErrorMap("Command timed out after 100 millisecond(s)"));
This here is a diff between 2 commits, not the final commit and the main branch.

2023-05-09 10:58 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/RedisSingleFaultCommandTimeoutExceptionAnalysisConfigurationFile.java
> +        filibusterAnalysisConfigurationBuilderRedisExceptions.exception("io.lettuce.core.RedisCommandTimeoutException", createErrorMap("Command timed out after 100 millisecond(s)"));
This is a diff between 2 commits btw, and not between this PR and the main branch

2023-05-11 16:12 UTC, cmeiklejohn requested changes
I partially reviewed this, please address comments on GitHub and then I'll review the remainder.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/Constants.java
> +    final public static String REDIS_MODULE_NAME = "RedisClient";
It would be nice to leave a comment about what actually uses this constant and where the name `RedisClient` comes from.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +
spacing.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableInstrumentation = false;
this should be set the way it's set in the other interceptors, no?

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableServerCommunication = false;
this should be set the way it's set in the other interceptors, no?  I thought the other places checked a system property or similar for this.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        this.contextStorage = new ThreadLocalContextStorage();
shouldn't there be a second constructor that takes the context storage?  I think the others have this.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        logger.log(Level.INFO, "RedisIntermediaryInterceptor: invoke() called");
I think the other loggers prefix their messages with Filibuster so it's easier to find in the log, right?

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        String redisMethodName = invocation.getMethod().getName();
I think a comment here would be useful to describe the possible values that this will be set to.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        CallsiteArguments callsiteArguments = new CallsiteArguments(invocation.getClass(), Arrays.toString(invocation.getArguments()));
Are you sure invocation.getClass is correct here? I think in the other interceptors it's used for the type of the object passed to arguments?

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Is there a possibility that the redis client uses a different port for each execution (since, it's automatically started by test containers?). This would make this non-deterministic.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        JSONObject forcedException = filibusterClientInstrumentor.getForcedException();
I know we're not using failure metadata -- probably useful to actually check and throw if it's set to indicate to the user that the option is not supported instead of silently fail.  It's always better to throw instead of silently failing.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            throw t;
What's this throw?

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        if (result != null) {  // e.g., when you query a key that is saved in Redis, result is null if key not in Redis
I do not understand what this block is doing.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        try {
This section is very dense and if you don't know the details of the library, hard to understand.  I would suggest use more spacing, use functions, comment heavily.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        return method.getReturnType().cast(result);
Again, unclear what this is doing and hard to code review without comments.

2023-05-11 16:12 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        } else if (exceptionNameString.equals("io.lettuce.core.RedisConnectionException")) {
Aren't there more exception types?

2023-05-11 20:26 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableInstrumentation = false;
Hey, this is actually the way it is set in the `FilibusterClientInterceptor`. The function shouldInstrument in `RedisInterceptor` calls `instrumentation.helpers.Property.getInstrumentationEnabledPropert`. `getInstrumentationEnabledPropert` reads from the system property `INSTRUMENTATION_ENABLED`.

2023-05-11 20:29 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableServerCommunication = false;
Hey, this is actually the way it is set in the `FilibusterClientInterceptor`. It reads from a system property. The function `shouldInstrument` in `RedisInterceptor` calls `instrumentation.helpers.Property.getInstrumentationServerCommunicationEnabledProperty`. `getInstrumentationServerCommunicationEnabledProperty` reads from the system property `INSTRUMENTATION_SERVER_COMMUNICATION_ENABLED`.

2023-05-11 20:34 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        this.contextStorage = new ThreadLocalContextStorage();
I could not find such constructor in grpcs or armeria.http client and server interceptors. Which interceptors have it?

2023-05-11 20:52 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        logger.log(Level.INFO, "RedisIntermediaryInterceptor: invoke() called");
Good idea, I have added a prefix to my log statements. The grpcs or armeria.http interceptors do not add such prefixes.

2023-05-11 20:58 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            throw t;
That's the exception thrown in case method.invoke or interceptedObject.getClass().getMethod throws. I have added a comment.

2023-05-11 22:19 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        logger.log(Level.INFO, "RedisIntermediaryInterceptor: invoke() called");
yeah, they don't and should be fixed, that's a problem.  but, the client instrumented does, for example.

2023-05-11 22:20 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        this.contextStorage = new ThreadLocalContextStorage();
oh perhaps this is only done in the Otel variant, disregard

2023-05-11 22:21 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableServerCommunication = false;
ok

2023-05-11 22:21 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    public static Boolean disableInstrumentation = false;
ok

2023-05-12 01:34 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        logger.log(Level.INFO, "RedisIntermediaryInterceptor: invoke() called");
Sure, I have added prefixes to the grpcs and armeria.http interceptors as well

2023-05-12 03:06 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        if (result != null) {  // e.g., when you query a key that is saved in Redis, result is null if key not in Redis
I have refactored the code and rephrased the comment

2023-05-12 03:20 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        CallsiteArguments callsiteArguments = new CallsiteArguments(invocation.getClass(), Arrays.toString(invocation.getArguments()));
What do I pass as a class if the method has multiple arguments?

2023-05-12 03:22 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        CallsiteArguments callsiteArguments = new CallsiteArguments(invocation.getClass(), Arrays.toString(invocation.getArguments()));
I could pass as class `invocation.getArguments().getClass()`, but that would just evaluate to object[]

2023-05-12 03:34 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
I don't think this is an issue. I am creating the RedisConnection instances by either:

1. Using the singelton class `RedisClientService`. The client and its connection string would not change in that case.
2. Using the parameterless constructor `RedisInterceptorFactory`. The `redisConnectionString` is passed on from the `getProxy` method to the `RedisInterceptor` class. The same connection string is always reused for the same client.

2023-05-12 03:46 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Sure, *in your code* it's not an issue.  But, I'd imagine that test code written by someone else could use a `@BeforeEach` block to start a new Redis container for each test on a random port `bind(0)`, thereby making it so each test uses a container at a different port number.

Right?

2023-05-12 04:02 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Yes, but the redisConnectionString (formatted: "redis://%host_address:%port") still uniquely identifies the Redis instance.

My idea was: Assume there is service A with two Redis instances X and Y. Each instance would be started at a different port. Both services will share the same host address. I need to be uniquely able to identify each of these instances to inject failures in each of them.

2023-05-12 04:07 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        } else if (exceptionNameString.equals("io.lettuce.core.RedisConnectionException")) {
Yes, I will add more exception types in a separate PR

2023-05-12 04:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Yes, but here's the problem.

- In execution 1 where there are no faults, you get port 10 and you generate an identifier by hashing that connection string to hash1 for it using that port number.
- Now, in execution 2 which is generated by Filibuster, you want to inject a fault for call hash1.  But, when you run the test *again* it uses a different port number.  it uses port 20, so it generates hash2.  Filibuster tries to inject a fault on hash1, but there is no hash1 because the second time you ran the test it has a different port number.

This is the same problem we have with data nondeterminism, etc.  You cannot use the port number *unless you assume that every single time you run the test the port number will always be the same.*  Since this code is in the application you are testing, you cannot make that guarantee.

Does that make sense?

2023-05-12 04:13 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Generally, you're making a decision here about how the application you're testing must be written based on an application that you yourself have written: this is almost always a bad decision. 

I suggest you make this option configurable using a property -- so, that based on how the property is set, you use host, port, or something else. In your test application, you can use port, because that works for you.  For other applications that might be running locally with Docker Compose where things might run on random ports, the *hostname* without port might be a better option.

2023-05-12 04:15 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
If you do this, when you are testing your application that uses redis://localhost:port1 and redis://localhost:port2 it works.

But, if I ran my Redis with Docker Compose -- which, is often the case -- it might be redis://redis1:4379 and redis://redis2:4379 using two different virtual IPS on localhost (redis1 : 127.0.0.1, redis2: 127.0.0.2, whatever.)

2023-05-12 04:16 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
(for what it's worth, the default test container is going to bind to *all localhost IPs by binding to 0.0.0.0 -- the alias for all local sockets with the same port*, but you don't need to do that.  you could bind to a specific virtual IP only.)

2023-05-12 04:20 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Oh thank you for pointing that out. I did not consider the case where Redis containers are started in the @BeforeEach. I will drop the port for now. I will create a separe issue that addresses adding a configurable property to use the port.

2023-05-12 04:25 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Sounds good.

Generally speaking, whenever we're dealing with values that must be deterministic, we need to:

- think through our assumptions about why we think a particular value will be deterministic and could they easily be not - data, ports, random numbers, user ids, all of this, when designed well, should be, but often in reality, is not because the developers often do not think about determinism when writing code for their job.
- make it all configurable, basically.

2023-05-12 04:27 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
If you want to do the property later, that's fine.  But, the default for everything in Filibuster so far is to opt for assuming determinism with a property to relax it.  

So, following that model to keep the library idiomatic, I would do:

- Default with full connection string.
- Property to remove port number usage and use only the hostname.  I would probably make the property like `filibuster.test.redis.nondeterminisic_port_numbers` and default it to false (similar to how we default data nondeterminism to false in the properties.

2023-05-12 04:28 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Please link the issue here once you open it.

2023-05-12 04:34 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
Gotcha, thanks. I will leave it as it is for now then. I will add the property to optionally drop the port in a separate PR.

2023-05-12 04:36 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
https://github.com/filibuster-testing/filibuster-java-instrumentation/issues/134

2023-05-12 06:23 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        Callsite callsite = new Callsite(redisConnectionString, REDIS_MODULE_NAME, redisMethodName, callsiteArguments);
I have just added the port nondeterminism property to this PR in the last commit. I will close issue #134 as it is not needed anymore.

2023-05-12 06:25 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        } else if (exceptionNameString.equals("io.lettuce.core.RedisConnectionException")) {
#135

2023-05-13 18:08 UTC, cmeiklejohn approved these changes

2023-05-13 18:33 UTC, merged