Temp fix wasFaultInjectedOnService for non-grpc and non-services
filibuster-testing/filibuster-java-instrumentation pull request #166
Opened 2023-05-31 22:24 UTC by MichaelA-ops

Closes #162

2023-05-31 23:08 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/assertions/Grpc.java
> +        if (serviceName != null && serviceName.toLowerCase(Locale.ROOT).contains("service")) {
Hi @cmeiklejohn , point 1 in #162 says I should throw if the format doesn't match a GRPC service. I am not sure how I could tell from the service name whether it's a GRPC service.

2023-05-31 23:55 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/assertions/Grpc.java
> +        if (serviceName != null && serviceName.toLowerCase(Locale.ROOT).contains("service")) {
For now, just check */*

2023-06-01 00:05 UTC, cmeiklejohn requested changes

2023-06-01 00:05 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/Assertions.java
> +    public static boolean wasFaultInjected(String uri) {
Was this a necessary change?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/assertions/Grpc.java
> +            throw new FilibusterRuntimeException("Service name does not indicate a GRPC service.");
Use that unsupported API exception.

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterSyncGetTest.java
> -            assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the expected Redis service: " + t);
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterSyncGetNonExistingKeyTest.java
> -            assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the Redis module: " + t);
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterSyncGetDefaultTest.java
> -            assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the Redis module: " + t);
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterRetryTest.java
> -                assertTrue(wasFaultInjectedOnService("io.lettuce.core.RedisFuture"), "Fault was not injected on the Redis module");
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterByzantineStringTest.java
> -            assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the Redis module");
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterByzantineByteArrTest.java
> -            assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the Redis module");
Can you call this and make sure it throws?

2023-06-01 00:05 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/redis/JUnitRedisFilibusterBuggyFallbackByzantineTest.java
> -                assertTrue(wasFaultInjectedOnService("io.lettuce.core.api.sync.RedisStringCommands"), "Fault was not injected on the Redis module");
Can you call this and make sure it throws?

2023-06-01 00:59 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/assertions/Grpc.java
> +        if (serviceName != null && serviceName.toLowerCase(Locale.ROOT).contains("service")) {
`wasFaultInjectedOnService` is mostly called with strings in other formats though. For example:

https://github.com/filibuster-testing/filibuster-java-instrumentation/blob/f5437c69529602c9d92e7e9e897e845a91a18784/src/test/java/cloud/filibuster/functional/java/basic/BasicTest.java#L81

2023-06-01 03:25 UTC, cmeiklejohn requested changes
Looks good, but I need you to bump the version and the CHANGELOG since you changed a core API.

2023-06-01 03:33 UTC, cmeiklejohn approved these changes

2023-06-01 03:46 UTC, merged