Create conditional for byzantine fault injection
filibuster-testing/filibuster-java-instrumentation pull request #168
Opened 2023-06-05 03:36 UTC by MichaelA-ops

2023-06-12 17:39 UTC, cmeiklejohn commented
Once #171 is done, can we finish up this one?

2023-06-30 13:59 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +                } catch (Throwable e) {
Why did this have to change?  Isn't this only runtime exceptions?

2023-06-30 14:09 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +        if (response != null) {
What about the else condition?

2023-06-30 14:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +                            filibusterClientInstrumentor.afterInvocationComplete(className, returnValueProperties, statusCode);
Did you verify this doesn't get called with transformer fault and still gets called for no-faults?

2023-06-30 14:14 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/grpc/JUnitFilibusterTransformerGRPCTest.java
> +        assertTrue(testExceptionsThrown.contains("expected: <Hello, world!!> but was: <Hello, !!>"));
How does the transformer know to change that specific field?

2023-06-30 14:20 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/java/grpc/JUnitFilibusterTransformerGRPCTest.java
> +        assertTrue(testExceptionsThrown.contains("expected: <Hello, world!!> but was: <Hello, !!>"));
Rather, when the RPC is made to world and you inject null, what does Hello receive from World?  A response?  An exception?

2023-06-30 18:18 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +        if (response != null) {
I can't define a `whenComplete` for a null response, so nothing needs to be done in the else case

2023-06-30 18:38 UTC, MichaelA-ops commented on src/test/java/cloud/filibuster/functional/java/grpc/JUnitFilibusterTransformerGRPCTest.java
> +        assertTrue(testExceptionsThrown.contains("expected: <Hello, world!!> but was: <Hello, !!>"));
The test issues an intercepted call to the hello service. This call has the name field set to "_world_". The hello service sends an HTTP response back with the message "Hello, _world_!!".

In the first execution after the reference run, we inject the value `null` as the message of the request being issued to the hello service. Therefore, the response coming from the hello service is just "Hello, !!"; without any name.

2023-06-30 18:52 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +                            filibusterClientInstrumentor.afterInvocationComplete(className, returnValueProperties, statusCode);
Thanks for pointing that out! Fixed it in last commit.

2023-06-30 18:52 UTC, MichaelA-ops commented on src/test/java/cloud/filibuster/functional/java/grpc/JUnitFilibusterTransformerGRPCTest.java
> +        assertTrue(testExceptionsThrown.contains("expected: <Hello, world!!> but was: <Hello, !!>"));
I rephrased the comment in my last commit

2023-06-30 22:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +        if (response != null) {
If that's true, then we need to write a different transformer that does some sort of other transformation, because for this to be considered "complete" we need to have the plumbing in for the whenComplete so we don't have to when we go to actually start doing interesting BFI.

2023-06-30 22:10 UTC, cmeiklejohn requested changes
See comment.

2023-07-07 07:47 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/armeria/http/FilibusterDecoratingHttpClient.java
> +        if (response != null) {
Instead of returning a null, I am now building an `HTTPResponse` object with null as content. We don't need to handle `whenComplete` separately for null reponses/transformer faults anymore.

For clarity, I also added a new API path and restructured the test.

2023-07-07 13:24 UTC, cmeiklejohn approved these changes

2023-07-07 14:25 UTC, merged