BFI should also do bit flip
filibuster-testing/filibuster-java-instrumentation pull request #171
Opened 2023-06-07 06:19 UTC by MichaelA-ops

2023-06-07 14:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +        return this.transformerByzantineFault;
Shouldn't this and the associated variable be a map from DEI's to objects or something to support multiple simultaneous byzantine faults being injected?

2023-06-07 14:58 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformString.java
> +    public boolean hasNext() {
Shouldn't this be in the interface?

2023-06-07 15:01 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformer.java
> +    T transform(T payload, T accumulator, int idx);
Why does index have to be passed explicitly here?  This isn't a very general interface, as not everything will have an index.  Couldn't this just be the accumulator, since you're not using the accumulator in your example.

For example, pass the next index to mutate into the accumulator and thread it through each execution.

2023-06-07 15:59 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +import cloud.filibuster.junit.configuration.examples.redis.byzantine.transformers.ByzantineTransformString;
Perhaps a better name for this is ByzantineStringTransformer, to make clear it implements this interface, it also reads a bit nicer.

2023-06-07 16:03 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
This doesn't seem right.  You're not returning an exception here and this will propagate to other places.  We need to report this differently.  For example, it should show as fault injected in the UX, but the request *does* success, just with an injected value.

2023-06-08 00:37 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformer.java
> +    T transform(T payload, T accumulator, int idx);
Yeah, I wasn't using the accumulator in my current implementation. I changed the interface and added a generic for the accumulator and adjusted the implementation class accordingly

2023-06-08 00:43 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
Yes, we need to create an _afterInvocationWithByzantineFault_ in the client instrumentor for BFI. I've been using the afterInvocationWithException as I couldn't find a better alternative

2023-06-11 05:58 UTC, MichaelA-ops commented
New stuff added to this PR:

- Inject transformer Byzantine faults
- Faults are generated inductively, not up front
- Implementation class and unit test for transformer BFI for strings
- Using a different background colour for Byzantine faults
- Implementing `afterInvocationWithByzantineFault` and using it instead of `afterInvocationWithException` for BFI

<img width="1108" alt="Screenshot 2023-06-11 at 01 50 39" src="https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/74309722/9709e903-dbbb-4101-a859-9a2685c87c4d">

2023-06-11 06:05 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
Created `afterInvocationWithByzantineFault` and now using it for both normal and transformer Byzantine faults

2023-06-12 02:59 UTC, cmeiklejohn commented
in the UX, the injected response should look the same as the response without FI: so like 'example' int he normal execution and 'examp1e' in the BFI execution

2023-06-12 03:00 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformationResult.java
> +    public JSONObject accumulator;
Shouldn't this be parameterized?  It isn't always going to be a JSON object, right?

2023-06-12 03:04 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/byzantine/redis/RedisSingleGetBasicStringByzantineFaultAnalysisConfigurationFile.java
> +            filibusterAnalysisConfigurationBuilderRedisExceptions.byzantine(new ByzantineStringFaultType(), value);
Can you explain what is happening here?  This isn't clear to me.

2023-06-12 03:06 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
I don't know what "normal" vs. "transformer" Byzantine faults are.

2023-06-12 03:06 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +            invocationCompletePayload.put("execution_index", distributedExecutionIndex.toString());
Should this method be synchronized?  Are the other variants of this?

2023-06-12 03:19 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
Transformer byzantine faults are those where a transformer function is used. Basically what this PR introduces.

2023-06-12 03:20 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            filibusterClientInstrumentor.afterInvocationWithException(sByzantineFaultValueString, sByzantineFaultValueString, additionalMetadata);
With normal byzantine faults, I meant the case when we hard-coded some type-specific values that are injected

2023-06-12 03:32 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/byzantine/redis/RedisSingleGetBasicStringByzantineFaultAnalysisConfigurationFile.java
> +            filibusterAnalysisConfigurationBuilderRedisExceptions.byzantine(new ByzantineStringFaultType(), value);
I don't need to use a HashMap anymore for communicating a Byzantine fault value to `FilibusterAnalysisConfiguration.java`. Instead, I just communicate the value directly as well as its type.

2023-06-12 03:32 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/byzantine/redis/RedisSingleGetBasicStringByzantineFaultAnalysisConfigurationFile.java
> +            filibusterAnalysisConfigurationBuilderRedisExceptions.byzantine(new ByzantineStringFaultType(), value);
The hashmap was an artifact from the analysis configuration files of exceptions

2023-06-12 03:35 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +            invocationCompletePayload.put("execution_index", distributedExecutionIndex.toString());
`afterInvocationWithException` is not synchronised. I haven't worked with multi-threading in Java before. Should I synchronise `afterInvocationWithByzantineFault`?

2023-06-12 03:46 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformationResult.java
> +    public JSONObject accumulator;
I am actually thinking of fixing the accumulator as a JSONObject. The accumulator needs to contain the original value from the reference execution as well as some further information about the current test execution (e.g., idx of mutated char in case of strings or key in case of hashmaps). This is best represented as a JSONObject. Otherwise, using generics would overcomplicate the code in the FilibusterCore.

2023-06-12 03:47 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformationResult.java
> +    public JSONObject accumulator;
What do you think?

2023-06-12 04:14 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +            invocationCompletePayload.put("execution_index", distributedExecutionIndex.toString());
`afterInvocationWithException` is not synchronised

2023-06-12 16:39 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +     * @param accumulator containing any additional information that should be communicated to the server and used in
I'm a little nervous about this change, as I know sometimes executions are compared to determine if they are the same by comparing the faultsToInject value.  In this case, there is a potential risk where two fault injections, derived through different types of iterators, that are the same are not considered redundant.

2023-06-12 16:40 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/byzantine/redis/RedisSingleGetBasicStringByzantineFaultAnalysisConfigurationFile.java
> +            filibusterAnalysisConfigurationBuilderRedisExceptions.byzantine(new ByzantineStringFaultType(), value);
OK, this isn't exactly clear from reading.  Can you explicitly put a comment in to indicate?

2023-06-12 16:42 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +            // Instead, we use JSONObject.NULL (https://developer.android.com/reference/org/json/JSONObject.html#NULL)
Do we know if other JSON parsers will treat/handle this correctly?  Why not just set metadata to an empty object `{}`?

2023-06-12 16:44 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/byzantine/redis/RedisSingleGetStringByzantineFaultAnalysisConfigurationFile.java
>          // Potentially use junit-quickcheck to generate the possible values -> Would make the tests more "flaky"
You can remove this comment, not necessary now.

2023-06-12 16:52 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +     * @param accumulator containing any additional information that should be communicated to the server and used in
Can you open an issue for tracking this so we do not forget?

2023-06-12 16:53 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
>              ByzantineFaultType<?> byzantineFaultType = (ByzantineFaultType<?>) byzantineFault.get("type");
Do you need a try/catch if this cast fails?

2023-06-12 16:54 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            value = byzantineFaultType.cast(value);
Do you need a try/catch if this cast fails?  (User provides value that cannot be cast to this value?)

2023-06-12 16:55 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            logger.log(Level.WARNING, logPrefix + "The byzantineFault either does not have the required key 'value' or 'accumulator'");
It might be useful to actually put a conditional in so you can tell the user which is null/empty.

2023-06-12 16:55 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            return null;
Also, shouldn't you be throwing a `FilibusterFaultInjectionException` here if we can't inject a fault?

2023-06-12 16:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            ByzantineFaultType<?> byzantineFaultType = (ByzantineFaultType<?>) byzantineFault.get("type");
Protection against failed cast?  (Class doesn't implement interface)

2023-06-12 16:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            value = byzantineFaultType.cast(value);
Protection against failed cast?  (Value cannot be cast to type.)

2023-06-12 16:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
>              logger.log(Level.WARNING, logPrefix + "The byzantineFault either does not have the required key 'type' or 'metadata'");
It might be useful to actually put a conditional in so you can tell the user which is null/empty.

2023-06-12 16:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
>              return null;
Also, shouldn't you be throwing a FilibusterFaultInjectionException here if we can't inject a fault?

2023-06-12 16:59 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/RedisTransformStringAnalysisConfigurationFile.java
> +                .name("java.byzantine.transform_string")
Should this be more specific -- like, have Redis in the name?

2023-06-12 17:01 UTC, cmeiklejohn commented on src/main/resources/html/test_execution_report/index.html
> +            background-color: coral;
I don't see coral in your screenshot.

2023-06-12 17:02 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformationResult.java
> +    public JSONObject accumulator;
OK, that works for now.  Open an issue to track the creation of a non-JSONObject accumulator.

2023-06-12 17:29 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +import org.jetbrains.annotations.NotNull;
Should this be the `javax.annotation` version that you are using elsewhere?

2023-06-12 17:30 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +import cloud.filibuster.junit.configuration.examples.redis.byzantine.transformers.ByzantineTransformer;
`ByzantineTransformer` shouldn't be in the 'examples' namespace: it's a core library.  Probably the same as the result as well.

2023-06-12 17:31 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                JSONObject transformerByzantineFaultObject = faultObject.getJSONObject("transformer_byzantine_fault");
Check key before access.

2023-06-12 17:32 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                if (transformationResult.hasNext) {
I think, in terms of extensibility and cleanliness, `hasNext` should be a function, not a public variable.

2023-06-12 17:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                            logger.warning("[FILIBUSTER-CORE]: transformerByzantines: Could not find class for transformer: " + transformerClassName + ". Skipping...");
Should this throw a fault injection exception?

2023-06-12 17:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
>                          logger.warning("[FILIBUSTER-CORE]: Either the key 'type' or 'metadata' was not defined for a byzantine" +
Should this throw a fault injection exception?

2023-06-12 17:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    JSONObject errorObject = (JSONObject) obj;
Protection against this cast failure?

2023-06-12 17:37 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                        logger.warning("[FILIBUSTER-CORE]: transformerByzantines: Either the key 'transformer', 'transformerClassName' or 'type' does not exist. Skipping...");
Should this throw a fault injection exception?  The reason I keep harping on this is because no one is going to look at these log messages and then when something is configured wrong -- they just don't see the fault injected.  It's not user friendly.  (We should still log, but probably throw as well.)

2023-06-12 17:38 UTC, cmeiklejohn requested changes
First pass of feedback.  Please make these changes and then I'll do another review.

2023-06-12 17:38 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +    @SuppressWarnings("unchecked")
Why is this suppression needed?

2023-06-12 23:01 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/redis/byzantine/transformers/ByzantineTransformationResult.java
> +    public JSONObject accumulator;
#177

2023-06-12 23:07 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +     * @param accumulator containing any additional information that should be communicated to the server and used in
#178

2023-06-12 23:50 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +            // Instead, we use JSONObject.NULL (https://developer.android.com/reference/org/json/JSONObject.html#NULL)
The hashmap `metadata` is an artifact from the exception injection that we do not need anymore for BFI. Instead, we just communicate the value to be injected.

The cast functions of the faults types (e.g., `ByzantineStringFaultType`) convert `JSONObject.NULL` to a `null`. It is not dependent on the JSON parser.

2023-06-12 23:52 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +            // Instead, we use JSONObject.NULL (https://developer.android.com/reference/org/json/JSONObject.html#NULL)
Setting `value` to an empty string might be problematic in case we want to inject the actual empty string as a byzantine value. We need to be separately able to inject `null` and the empty string.

2023-06-13 00:09 UTC, MichaelA-ops commented on src/main/resources/html/test_execution_report/index.html
> +            background-color: coral;
The background colour of the Byzantine fault in the screenshot is coral/orange. Should we use a different/more distinct colour?

2023-06-13 01:00 UTC, cmeiklejohn commented
I don't see coral.  What am I missing? 
![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/ba776926-922d-4c72-a3d5-ba453647b8a6)

2023-06-13 01:01 UTC, cmeiklejohn commented
Oh, perhaps my monitor is just not good enough to distinguish the red from the coral, they look almost identical.

2023-06-13 01:02 UTC, cmeiklejohn commented
It looks better on the MacBook display, but not much different on my external widescreen.

2023-06-13 01:03 UTC, cmeiklejohn commented
Bah, OK, just leave it as it is for now.

2023-06-13 01:06 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +            // Instead, we use JSONObject.NULL (https://developer.android.com/reference/org/json/JSONObject.html#NULL)
I guess my question is somewhat different:

* If I write a JSON file and set a key to JSONObject.NULL: what appears in the actual JSON file that's been written?
* If I was to parse that file in Python using it's JSON parser -- thinking, writing an analysis file in Java and reading in Python instrumentation -- will that be parsed correctly?

2023-06-13 01:26 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +            // Instead, we use JSONObject.NULL (https://developer.android.com/reference/org/json/JSONObject.html#NULL)
I've just tested it out. The JSON file will have a `null` value for the key that was set to `JSONObject.NULL`. I could read the file with Python's `json.loads` correctly. In Python's dict, the key had the value `None`.

2023-06-13 02:20 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                JSONObject transformerByzantineFaultObject = faultObject.getJSONObject("transformer_byzantine_fault");
I check whether the key exists in line 253. Do you mean I should check whether its type is JSONObject?

2023-06-13 03:44 UTC, cmeiklejohn commented
update that changelog yo

2023-06-13 03:44 UTC, cmeiklejohn commented
no need to bump version, we'll target all of this at 1.8.0

2023-06-13 19:34 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/RedisTransformStringAnalysisConfigurationFile.java
> +                .pattern("io.lettuce.core.api.sync.RedisStringCommands/get\\b");
Should this be done for set as well?

2023-06-13 19:37 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/test_executions/AbstractTestExecution.java
> +    public ConcreteTestExecution getCompletedSourceConcreteTestExecution() {
It's unclear to me how this will be set for like, the second or third iterations of testing.  Is this always the execution before or the original source execution.

2023-06-13 19:43 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
>  import java.util.*;
Is it possible for you to fix this wildcard import in this file?  I know you didn't introduce it in this PR, but while we are here...

2023-06-13 19:44 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/test_executions/AbstractTestExecution.java
> +    public ConcreteTestExecution getCompletedSourceConcreteTestExecution() {
It's always the execution before. Its accumulator has the originalValue field though and the idx of the last mutated char (in case of strings).

2023-06-13 19:44 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
Can you add a test into the repo where there is a Redis BFI and an RPC before and after?  I want to see what the fault injection order looks like: for example, the search order of the faults?

2023-06-13 19:45 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
Do we run the risk of a scenario where if the transformer generates the same fault over and over that this won't prevent termination?

2023-06-13 19:46 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    @SuppressWarnings("unchecked")
Why?

2023-06-13 19:49 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    @SuppressWarnings("unchecked")
Why?

2023-06-13 19:52 UTC, cmeiklejohn commented
This is looking good, only a few minor things left to address.

2023-06-13 19:56 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/test_executions/AbstractTestExecution.java
> +    public ConcreteTestExecution getCompletedSourceConcreteTestExecution() {
OK, can you add a comment to make that explicitly clear in the code?

2023-06-13 19:56 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/RedisTransformStringAnalysisConfigurationFile.java
> +                .pattern("io.lettuce.core.api.sync.RedisStringCommands/get\\b");
The way we have BFI currently is to modify the return value. `set` just returns an `OK`. Do you mean we should BFI on the input of the `set` method?

2023-06-13 19:58 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/RedisTransformStringAnalysisConfigurationFile.java
> +                .pattern("io.lettuce.core.api.sync.RedisStringCommands/get\\b");
OK, I get it.

2023-06-13 20:13 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
It depends on how the `transform` and `getNewAccumulator` methods of the `ByzantineTransformer` are implemented. I don't think we run this risk for strings.

2023-06-13 20:17 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
Can we make a faulty injector that just injects the same fault over and over (and returns the same accumulator) to see what the behavior is?  I just want to make sure we understand completely how this thing will work.

2023-06-13 21:04 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
Just added the unit test `JUnitRedisFilibusterExhaustiveExceptionAndStringTransformerTest`. DFS seems to be working correctly. All Byzantine faults are injected before exceptions.

2023-06-13 21:05 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
I came across a bug though. We need to check when the reference execution returns a null (e.g., in the reference execution, you call `get` on a key that is not in the DB). I will create a new PR for this though.

2023-06-13 21:15 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
#181

2023-06-14 01:19 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
I have just tried that out with a faulty accumulator that only insert "X" at char 0. 4 BFI tests were executed until `abstractIsExploredExecution` turned true and the test scheduling ended

2023-06-14 01:23 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +                returnValue.put(entry.getKey(), entry.getValue() == null ? JSONObject.NULL : entry.getValue());
Can you add a comment here to indicate why this is being done -- you might remember now, but you might not several months from now.  I surely won't.

2023-06-14 01:26 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
Are you asking me or telling me?

2023-06-14 01:26 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
You fixed this, right?

2023-06-14 01:28 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
Yes

2023-06-14 01:28 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
And added in `JUnitRedisFilibusterExhaustiveExceptionAndStringTransformerTest` two cases where the return is `null` and an empty string

2023-06-14 01:32 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
OK, you can mark #181 as completed then.

2023-06-14 01:33 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    if (transformationResult.hasNext()) {
Sure. Merging this PR would have automatically closed it.

2023-06-14 01:33 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                        createAndScheduleAbstractTestExecution(filibusterConfiguration, distributedExecutionIndex, new JSONObject(faultObject.toString()), /* isTransformedByzantineFault= */true);
Why is this still in beforeInvocation?  Is this necessary?

2023-06-14 01:34 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                        createAndScheduleAbstractTestExecution(filibusterConfiguration, distributedExecutionIndex, new JSONObject(faultObject.toString()), /* isTransformedByzantineFault= */true);
Oh, you're doing non-transformers in before and transformers in the end invocation?  Any reason both couldn't be in the end invocation -- it's a bit split all over the place and this would be much cleaner if it could all be in a single location, right?

2023-06-14 01:37 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
I meant it as a question. If I remember correctly from the DEI paper, we check the the stack of executed tests to determine whether a test execution is repeated. Do we check the stack only up to a specific depth?

2023-06-14 01:39 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && (!abstractIsCurrentExecution || isTransformedByzantineFault)) {
No, it should be checking the entire stack.  So, that means that something isn't working correctly for BFI, because it's working for normal faults (otherwise, our tests would never terminate.). Something is different in 3 of those executions.  I suggest running your test and using a breakpoint at that line and investigate why the entire doesn't match the entry that's in the stack/queue.

(This is sort of why I had to write the test, to make sure things worked as expected.)

2023-06-14 02:14 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                        createAndScheduleAbstractTestExecution(filibusterConfiguration, distributedExecutionIndex, new JSONObject(faultObject.toString()), /* isTransformedByzantineFault= */true);
I would need to recreate the transformationResult object in the `endInvocation`. This would have a pretty high overhead.

2023-06-14 02:17 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                        createAndScheduleAbstractTestExecution(filibusterConfiguration, distributedExecutionIndex, new JSONObject(faultObject.toString()), /* isTransformedByzantineFault= */true);
For consistency, I moved the non-transformer BFI to the `endInvocation` as well. 

The LoC we are commenting on here is for scheduling the next execution in case of transformer BFI.

2023-06-15 04:13 UTC, cmeiklejohn commented
Please do not forget follow-up PR to remove use of byzantine with transformer in Filibuster libraries: Core, Instrumentor, etc.

2023-06-15 04:15 UTC, cmeiklejohn commented
Honestly, it would just be easier if you did that in this PR, actually.

2023-06-15 04:15 UTC, cmeiklejohn commented
I'll mark the files accordingly.

2023-06-15 04:16 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +    private JSONObject transformerByzantineFault;
transformerFault

2023-06-15 04:16 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +    public JSONObject getTransformerByzantineFault() {
transformerFault

2023-06-15 04:18 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/transformers/ByzantineTransformer.java
> +public interface ByzantineTransformer<PAYLOAD, CONTEXT> {
Do you mind adding Javadoc quickly to this method just so others know how to implement it?  

For example, transform is somewhat clear to me (what is the actual return supposed to be), but getResult for instance is not.

Otherwise, this interface looks good.

2023-06-15 04:19 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/transformers/ByzantineTransformer.java
> +
Rename module to Transformer from ByzantineTransformer.

2023-06-15 04:20 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/transformers/FaultyByzantineStringTransformer.java
> +        if (accumulator == null) {
I'm not clear when this will ever be null.  I thought you only called transform with accumulator ever and in the reference execution you called it with the result of getInitialAccumulator?

2023-06-15 04:20 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/test_executions/AbstractTestExecution.java
> +    public ConcreteTestExecution getCompletedSourceConcreteTestExecution() {
We shouldn't need this anymore, given you are getting the value from endInvocation, right?

2023-06-15 04:20 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/lint/analyzers/test_execution_report/RedundantRPCAnalyzer.java
> +            } else if (response.has("byzantine_fault")) {
transformer fault

2023-06-15 04:23 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/transformers/ByzantineStringTransformer.java
> +        if (accumulator == null) {
see my comment in the other transformer for this very line

2023-06-15 04:24 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +            if (jsonObject.has("transformer_byzantine_fault")) {
transformer_byzantine_fault -> transformer_fault

2023-06-15 04:27 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +        JSONObject transformerByzantineFault = filibusterClientInstrumentor.getTransformerByzantineFault();
transformer fault

2023-06-15 04:28 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +            return injectTransformerByzantineFault(filibusterClientInstrumentor, transformerByzantineFault, invocation.getMethod().getReturnType());
same

2023-06-15 04:28 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +    private static Object injectTransformerByzantineFault(FilibusterClientInstrumentor filibusterClientInstrumentor, JSONObject byzantineFault, Class<?> returnType) {
same

2023-06-15 04:29 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +    private static void setAccumulatorOnTransformerBF(JSONObject transformerBF, Accumulator<?, ?> accumulator) {
transformerBF -> transformer

2023-06-15 04:33 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterAnalysisConfiguration.java
> +        public Builder byzantineTransformer(Class<? extends ByzantineTransformer<?, ?>> transformer) {
transformer

2023-06-15 05:28 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/transformers/FaultyByzantineStringTransformer.java
> +        if (accumulator == null) {
Yeah, this is an artefact from the older implementation

2023-06-15 14:32 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +     * Return byzantine fault that needs to be injected.
fix comment

2023-06-15 14:34 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/FaultyRedisTransformStringAnalysisConfigurationFile.java
> +                .name("java.byzantine.transform_string.redis")
java.byzantine.transform_string.redis -> java.transformers.transform_string.redis

2023-06-15 14:35 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/RedisExhaustiveExceptionAndTransformerAnalysisConfigurationFile.java
> +                .name("java.byzantine.transform_string.redis")
name doesn't seem correct given the faults here?

2023-06-15 14:35 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/lint/analyzers/test_execution_report/RedundantRPCAnalyzer.java
> +            } else if (response.has("byzantine_fault")) {
no branch for transformer faults?

2023-06-15 14:41 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/RedisTransformStringAnalysisConfigurationFile.java
> +                .name("java.byzantine.transform_string.redis")
java.byzantine.transform_string.redis -> java.transformers.transform_string.redis

2023-06-15 15:04 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (byzantineFault.has("type") && byzantineFault.has("value")) {
Is this the other type of byzantine fault?

2023-06-15 15:06 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    logger.warning("[FILIBUSTER-CORE]: analysisFile, could not process transformer byzantine fault object.");
no byzantine

2023-06-15 15:06 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                    throw new FilibusterFaultInjectionException("[FILIBUSTER-CORE]: analysisFile, could not process transformer byzantine fault object.", e);
no byzantine

2023-06-15 15:07 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            if ((!abstractIsExploredExecution && !abstractIsScheduledExecution) && !abstractIsCurrentExecution) {
can we remove these extra parens?

2023-06-15 15:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +                if (byzantineFault.has("value")) {
byzantine

2023-06-15 15:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +                Object byzantineFaultValue = byzantineFault.get("value");
byzantine all over here

2023-06-15 15:10 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/lettuce/RedisInterceptor.java
> +                filibusterClientInstrumentor.afterInvocationWithByzantineFault(sByzantineFaultValueString,
I think we should also have an afterInvocationWithTransfomerFault

2023-06-15 16:20 UTC, cmeiklejohn commented on src/main/resources/html/test_execution_report/index.html
> +                    } else if (isByzantineFault) {
Duplicate.

2023-06-15 16:20 UTC, cmeiklejohn commented on src/main/resources/html/test_execution_report/index.html
> -                    var isByzantineFault = containsByzantineFaultKey(rpc.fault);
Duplicate for both types.

2023-06-15 16:20 UTC, cmeiklejohn commented on src/main/resources/html/test_execution_report/index.html
> +                        if(containsByzantineFaultKey(rpc.response) && containsAccumulator(rpc.response.byzantine_fault)) {
Same.

2023-06-15 16:21 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        // Byzantine faults are injected in the endInvocation since we need to know the response value.
Byzantine or transformer?

2023-06-15 16:22 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        // Byzantine faults are injected in the endInvocation since we need to know the response value.
e.g., if Byzantine -- the first faults you did -- just change the value, it surely doesn't need to know the response value to just inject a different value.  Is this actually transformer faults?

2023-06-15 16:23 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +    private void scheduleInitialByzantineFault(JSONObject payload, DistributedExecutionIndex distributedExecutionIndex) {
Transformer?

2023-06-15 18:27 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/configuration/examples/db/redis/RedisExhaustiveExceptionAndTransformerAnalysisConfigurationFile.java
> +                .name("java.byzantine.transform_string.redis")
The regex patterns are different here for each exception (unlike grpc where we mostly have `(.*/.*)`, so I create a new `FilibusterAnalysisConfiguration.Builder` for each exception or transformer fault, each with their own name and pattern.

2023-06-15 18:29 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/lint/analyzers/test_execution_report/RedundantRPCAnalyzer.java
> +            } else if (response.has("byzantine_fault")) {
We only had `afterInvocationWithByzantineFault` till now, so both transformer and byzantine faults were put under the same key `byzantine_fault` for reporting

2023-06-15 18:30 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/lint/analyzers/test_execution_report/RedundantRPCAnalyzer.java
> +            } else if (response.has("byzantine_fault")) {
That's going to change with `afterInvocationWithTransformerFault`

2023-06-15 18:34 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (byzantineFault.has("type") && byzantineFault.has("value")) {
Yes, the one we implemented first.

2023-06-15 18:44 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        // Byzantine faults are injected in the endInvocation since we need to know the response value.
It's actually both. I understood from a previous review that I should move both transformer and the older byzantine faults to the `endInvocation`.

2023-06-15 18:44 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        // Byzantine faults are injected in the endInvocation since we need to know the response value.
I'll rephrase the comment to reflect both transformer and byzantine faults

2023-06-15 18:45 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +    private void scheduleInitialByzantineFault(JSONObject payload, DistributedExecutionIndex distributedExecutionIndex) {
Please see previous comment. It's both transformer and Byzantine faults. I'll rename the method to reflect both.

2023-06-15 20:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/instrumentors/FilibusterClientInstrumentor.java
> +
remove empty line, not valid doc

2023-06-15 20:40 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        checkForByzantineAndTransformerFaults(payload, distributedExecutionIndex);
nitpick: why is this called " check" isn't it actually scheduling them?

2023-06-15 20:41 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                setValueOnTransformer(transformerFaultObject, (String) transformationResult.getResult());
could the naming be slightly better here, I'm not sure what this is actually doing

2023-06-15 20:43 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
Did you write a BFI test with dataNondeterminism = true?  

I suspect the only reason this returns true using BFI is because the value is encoded into the payload and that this will not work with dataNondeterminism = true (where, Redis DEI's will contain no arguments.). Unfortunately, most real world code will have to have this option set.

2023-06-15 21:35 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
I've just written one. `shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);` never evaluates to true. Should we remove it?

2023-06-15 22:18 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
Yeah, this logic is there for a reason, but that reason might be specific to it being called in `beforeInvocation` -- prior to adding it to the concrete execution, which is the reason it never evaluates that way. 

We need to figure out:

1.) Why it's in `beforeInvocation` and what scenario it prevents?
2.) If it is needed in the `endInvocation` call.

2023-06-15 22:19 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        scheduleInitialByzantineAndTransformerFaults(payload, distributedExecutionIndex);
I'm going to nitpick you again: isn't this *all* byzantine faults and only the *initial* transformer fault?

2023-06-15 22:28 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        scheduleInitialByzantineAndTransformerFaults(payload, distributedExecutionIndex);
We are removing Byzantine faults anyway in issue #184. For now, we can rename it to `scheduleByzantineAndTransformerFaults`. What do you think?

2023-06-15 22:34 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
In `beforeInvocation`, you hit the first if under the reference execution and schedule all of the faults.  When you are executing one of the fault executions -- and it reaches an RPC that was already scheduled for fault injection during the reference execution -- this prevents this from generating more test executions because the executions were already performed under the reference execution.

2023-06-15 22:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
Yes, I remember why this check is made.  The abstract executions are only partial -- so they only know the RPCs executed up-to-a-point; but, we might have executed an RPC after that and scheduled faults for it.

2023-06-15 22:38 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
For example,

* ref concrete will have RPCs (1 2 3) 
* abstract #2 will be (1 Fault2) -- we can't include 3 in the abstract because we don't know if 3 happening is conditional on 2 happening without fault, but the concrete execution that the abstract was generated from contains (1 2 3). therefore, when 3 happens, we don't want to schedule faults for it again so we check the concrete that it was generated from to see if 3 was in it, and if it was, we know we don't need to generate faults for it

2023-06-15 22:46 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +        scheduleInitialByzantineAndTransformerFaults(payload, distributedExecutionIndex);
Sure.

2023-06-15 22:49 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
What made you determine that it's never hit?  I literally copy/pasted that conditional into my branch in `endInvocation` and set a breakpoint on it and it evaluates to true.
![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/e954da5b-4094-4162-bceb-f5453afd67a0)

2023-06-15 22:57 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
Oh, you're never going to see this hit if you run tests that only have a single RPC in them, because it's only active when there's more than one RPC in the test.

2023-06-15 23:01 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
I have a failing test.

2023-06-15 23:09 UTC, cmeiklejohn commented
```        
StatefulRedisConnection<String, String> myStatefulRedisConnection = new RedisInterceptorFactory<>(statefulRedisConnection, redisConnectionString).getProxy(StatefulRedisConnection.class);
        RedisCommands<String, String> myRedisCommands = myStatefulRedisConnection.sync();

        myRedisCommands.get(key);
        myRedisCommands.get(key);
        myRedisCommands.get(key);
```

This test will trigger that if statement to get hit, because there are more than one RPC, and when you hit endInvocation for the second RPC in the non-reference execution, you'll hit this to avoid injecting faults for the first RPC.  That seems to be working correctly.

However, `suppressCombinations` doesn't work and the UX is also busted.  If I run that above with suppressCombinations on, I see it run tests anyway where combinations are present and faults are not rendered correctly.

See:

![image](https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/44939/9bf6efe1-06e1-437e-8fcc-25fb1c1f409c)

2023-06-15 23:25 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +            shouldGenerateNewAbstractExecutions = !currentAbstractTestExecution.sawInConcreteTestExecution(distributedExecutionIndex);
Assigned #186.

2023-06-15 23:44 UTC, merged