Filibuster option to fail test if fault is not injected
filibuster-testing/filibuster-java-instrumentation pull request #208
Opened 2023-07-13 06:14 UTC by MichaelA-ops

2023-07-14 04:27 UTC, cmeiklejohn commented
Is it possible to also make this a system property like data nondeterminism is?  See the FilibusterTestExtension to see how that is done.

2023-07-14 04:28 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/interceptors/FilibusterInvocationInterceptorHelpers.java
> +                if (expectedExceptionClass.equals(FilibusterFaultNotInjectedException.class)) {
Can you explain why this is here and what it is doing specifically for this option?

2023-07-14 04:30 UTC, cmeiklejohn commented on src/test/java/cloud/filibuster/functional/shouldFails/FilibusterRedisAsyncSetFailTest.java
> +            failIfFaultNotInjected = true)
Rather than place this in the shouldFails -- that directory is *only* supposed to be used for tests that fail that fail *after* junit finishes and is shutting down, therefore we can't catch the failure programmatically -- can you use expected= or some other try/catch?

2023-07-14 04:31 UTC, cmeiklejohn requested changes
See comments.

2023-07-17 22:40 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/junit/interceptors/FilibusterInvocationInterceptorHelpers.java
> +                if (expectedExceptionClass.equals(FilibusterFaultNotInjectedException.class)) {
I simplified the if-condition and added a comment

2023-07-17 22:42 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterConfiguration.java
> +        if (failIfFaultNotInjected == FAIL_IF_FAULT_NOT_INJECTED_DEFAULT) {
Why don't you just set this in the invocation interceptor from the property, then default to the annotation, like we do for all of the other properties?

2023-07-17 22:43 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/configuration/FilibusterConfiguration.java
> +        if (failIfFaultNotInjected == FAIL_IF_FAULT_NOT_INJECTED_DEFAULT) {
https://github.com/filibuster-testing/filibuster-java-instrumentation/blob/main/src/main/java/cloud/filibuster/junit/extensions/FilibusterTestExtension.java#L105-L110

2023-07-17 23:42 UTC, cmeiklejohn approved these changes

2023-07-17 23:42 UTC, merged