UX: Show fix message
filibuster-testing/filibuster-java-instrumentation pull request #217
Opened 2023-07-18 22:38 UTC by MichaelA-ops

2023-07-19 02:28 UTC, cmeiklejohn commented
Care to add a few screenshots here just so we can see it?

2023-07-19 02:29 UTC, cmeiklejohn commented
I'm assuming all of the error messages are not set correctly yet or I should assume that?

2023-07-19 02:35 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcStubbedRPCHasNoAssertionsException.java
> +                    "<li>" +
Third one shouldn't be here.  Should just be the verifyThat variants (2, I think.)

2023-07-19 02:36 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcThrownExceptionHasUnspecifiedFailureBehaviorException.java
> +                    "<li>" +
Should be all 4? variants of assertFaultThrows linked here.

2023-07-19 02:37 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcThrownExceptionHasUnspecifiedFailureBehaviorException.java
> +                    "<li>" +
I think there's actually more, it should link to all variants of asssertFaultThrows.

2023-07-19 02:37 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcSuppressedStatusCodeException.java
> +                            "Place test assertions in assertTestBlock instead." +
assertFaultPropagates() variants.

2023-07-19 02:38 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcAmbiguousThrowAndErrorPropagationException.java
> +                        "<a target=\"_blank\" href=\"https://filibuster-testing.github.io/filibuster-java-instrumentation/javadoc/cloud/filibuster/junit/statem/FilibusterGrpcTest.html#assertTestBlock
Should ask the user to remove an assertOnException or assertFaultPropagates as two different bullet points linking to each

2023-07-19 02:38 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcAmbiguousThrowAndErrorPropagationException.java
> +                        "<a target=\"_blank\" href=\"https://filibuster-testing.github.io/filibuster-java-instrumentation/javadoc/cloud/filibuster/junit/statem/FilibusterGrpcTest.html#assertTestBlock
like Remove a X, Remove a Y

2023-07-19 02:44 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcReadOnlyRPCUsedOutsideAssertOnExceptionException.java
> +                            "Potentially place assertions in assertTestBlock instead of assertOnException." +
just link to assertOnException variants and readOnlyRPC variants I guess?

2023-07-19 02:45 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcSideEffectingRPCUsedOutsideAssertOnExceptionException.java
> +                            "Potentially place assertions in assertTestBlock instead of assertOnException." +
just link to assertOnException variants and sideEffectingRPC variants I guess?

2023-07-19 02:45 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcMultipleFaultsInjectedException.java
> +                            "Place test assertion in assertTestBlock." +
link to assertOnFault variants

2023-07-19 06:38 UTC, MichaelA-ops commented
<img width="1015" alt="Screenshot 2023-07-19 at 02 35 53" src="https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/74309722/a8ce8660-43ad-4291-b908-1bb34ef82074">
<img width="1464" alt="Screenshot 2023-07-19 at 02 38 45" src="https://github.com/filibuster-testing/filibuster-java-instrumentation/assets/74309722/4672984a-b81d-4b73-b467-0d28c4530fae">

2023-07-19 07:11 UTC, cmeiklejohn requested changes
changelog = version 1.9.10

2023-07-20 16:10 UTC, cmeiklejohn commented
I want to make some changes to these message, I'm not 100% on them yet.

2023-07-20 16:11 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/exceptions/filibuster/FilibusterGrpcTestRuntimeException/FilibusterGrpcAmbiguousFailureHandlingException.java
> +                            "Write an assertion for the current fault combination using assertOnFault(CompositeFaultSpecification compositeFaultSpecification, java.lang.Runnable runnable)." +
Can we reformat the messages so it reads like 

"Write an assertion for the current fault combination using <LINK>assertOnFault(CompositeFaultSpecification compositeFaultSpecification, java.lang.Runnable runnable)</LINK>"

Having the entire thing a link is too difficult on the eyes.

2023-07-21 03:45 UTC, merged