Wrap DB exceptions in Transformers
filibuster-testing/filibuster-java-instrumentation pull request #272
Opened 2023-08-23 01:55 UTC by MichaelA-ops

2023-08-23 03:34 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
What does DB Exception represent?

2023-08-23 03:46 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
It's a class representing DB exceptions that I wrap in transformers.

2023-08-23 03:47 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
I could just use a JSONObject instead, but using a class with its own builder makes it more organised

2023-08-25 17:26 UTC, cmeiklejohn requested changes
see comments

2023-09-02 01:58 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
It shouldn't make a difference. Exception in this PR are wrapped in the class `DBExceptionTransformer`. The result of this transformation is a `DBException`, regardless of whether we write to a JSON file and read it back in.

2023-09-02 02:00 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
Just to be absolutely sure though, how do I make Filibuster write to a JSON file and read back in?

2023-09-05 15:16 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
There is a function in the configuration file super type that contains the code to write the file, you use the annotation and point it at the file to read it back in.

2023-09-05 15:17 UTC, cmeiklejohn requested changes
.

2023-09-09 02:01 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
I have just added a test where I am importing a `.fac` file containing a transformer-wrapped exception. The test is successful.

2023-09-09 02:01 UTC, MichaelA-ops commented on src/main/java/cloud/filibuster/instrumentation/libraries/dynamic/proxy/DynamicProxyInterceptor.java
> +            if (transformerFaultValue instanceof DBException) {
The file name is `RedisFilibusterTransformerExceptionWithAnalysisResourceFileTest`

2023-09-12 20:04 UTC, merged