An initial attempt to add test name in the test objects and expose it to the UI
filibuster-testing/filibuster-java-instrumentation pull request #77
Opened 2023-03-17 06:02 UTC by jiujiu1123

#66 

First attempt lmk if this approach is ill-advised.

2023-03-20 01:25 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/extensions/FilibusterTestExtension.java
> +                .testName(displayName)
What happens if there is no display are attribute?  Does this throw an exception?

2023-03-20 01:29 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> -    private ConcreteTestExecution currentConcreteTestExecution = new ConcreteTestExecution();
If you're setting this in the constructor, does this no longer need `@Nullable` then?  Is there any situtation where it might be null?

2023-03-20 01:29 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                currentConcreteTestExecution = new ConcreteTestExecution(nextAbstractTestExecution, this.filibusterConfiguration.getTestName());
Probably don't need `this` here, right?

2023-03-20 02:06 UTC, cmeiklejohn requested changes
This looks OK for now, but we'll have to do some refactoring when we display entire test suites in the UI instead of just a single test.

2023-03-30 06:32 UTC, jiujiu1123 commented on src/main/java/cloud/filibuster/junit/extensions/FilibusterTestExtension.java
> +                .testName(displayName)
According to the Doco,  getDisplayName() : "the display name of the test or container; never null or blank"

2023-03-30 06:33 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/extensions/FilibusterTestExtension.java
> +                .testName(displayName)
Test it manually with one of the tests that doesn't have a display name and see what it does, don't rely on the documentation.

2023-03-30 06:37 UTC, jiujiu1123 commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> -    private ConcreteTestExecution currentConcreteTestExecution = new ConcreteTestExecution();
https://github.com/filibuster-testing/filibuster-java-instrumentation/blob/9c660b5f7f246d9100048ed197fb1ca6a4518c11/src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java#L377 

I think this sets it to null so it's still possible

2023-03-30 06:38 UTC, jiujiu1123 commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +                currentConcreteTestExecution = new ConcreteTestExecution(nextAbstractTestExecution, this.filibusterConfiguration.getTestName());
you are absolutely right

2023-03-30 06:39 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/extensions/FilibusterTestExtension.java
> +                .testName(displayName)
OK, that's good.

2023-04-12 05:37 UTC, jiujiu1123 commented
Hey @cmeiklejohn I just did most of the test suite stuff. Would love to have some feedback :)

2023-04-12 15:46 UTC, cmeiklejohn commented on src/main/java/cloud/filibuster/junit/server/core/FilibusterCore.java
> +    private final UUID testUUID = UUID.randomUUID();
Add comment indicating what this is.

2023-04-12 15:52 UTC, cmeiklejohn requested changes

2023-04-12 15:52 UTC, cmeiklejohn commented on src/main/resources/html/test_suite_report/index.html
> +    <title>Filibuster Test Execution Report</title>
I think you need to verify that the titles are correct in these files.

2023-04-12 15:52 UTC, cmeiklejohn commented on src/main/resources/html/test_suite_report/index.html
> +    <h1 id='status'>Filibuster Test Coverage</h1>
"Coverage" probably isn't the correct name here.

2023-04-12 16:22 UTC, cmeiklejohn commented
One other thing that I am thinking: if I only ran a single test, I should go directly to the page with the test results when I open the plugin?

2023-04-13 04:54 UTC, jiujiu1123 commented
Lmk if these comments are resolved in the latest commit.

2023-04-14 19:06 UTC, cmeiklejohn commented
Please:

- [ ] Bump version (minor revision)
- [ ] Update CHANGELOG.

2023-04-14 20:18 UTC, cmeiklejohn approved these changes

2023-04-14 20:19 UTC, cmeiklejohn commented
Good to merge.

2023-04-14 20:22 UTC, merged